### ISSUE TITLE
Disable /bill

### ISSUE THREAD

**Issue by Quickslvr-FiveM** [Giana/g-billing#3]
Is there any way to disable the original /bill ?

**Comment by LightningCommunity** [comment]
> Is there any way to disable the original /bill ?

in qb-phone/server/main.lua at the end

**Comment by Giana** [comment]
Sorry, I received no notification for this! I double checked the code as of today and can confirm that in qb-phone/server/main.lua, there is a "bill" command and you can just comment that whole block out or disable it via adding a config flag or whatever you want. Just search "bill" in the file and you will find it toward the bottom (as of right now, at least).
