### ISSUE TITLE
Attempt to index nil value (local 'input')

### ISSUE THREAD

**Issue by Rorsterz** [Giana/g-billing#9]
I get an error for nil valve as attached photo but also ive noticed that i hadnt down one of the steps which im just a bit confused about on where to add that sql file note as Execute the query from g-billing.sql in your server's database. Thanks in advance
![Screenshot_9](https://user-images.githubusercontent.com/130359821/230882547-118864e0-a1df-4ba5-9c2d-3f6d566df8ad.png)

**Comment by Giana** [comment]
That step is extremely important as the entire billing script is centered around the database table you create via running the query I provided in the .sql file.

You need to run that query in your database/database management system for this script to operate. How you run a query depends on which database management system you're using, like HeidiSQL or MySQL WorkBench.

**Comment by Giana** [comment]
I pushed new code to master and this error should no longer occur when you don't pass in input (though this error not being handled previously wasn't actually breaking anything). However, you still have to run the query in your database for this script to work at all.
